name: ci-api
on:
  pull_request:
    branches: [master, main, demo, integration]

env:
  PROJECT_DIRECTORY: src
jobs:
  api-green-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16.17.0' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Update npm
        run: npm install -g npm@8
      - name: Install dependencies for linter
        run: |
          cd ${{ env.PROJECT_DIRECTORY }}
          npm i
      - name: Run linter
        run: |
          cd ${{ env.PROJECT_DIRECTORY }}
          npm run lint
      - name: Install dependencies
        run: |
          cd ${{ env.PROJECT_DIRECTORY }}
          npm i --legacy-peer-deps
      - name: Run tests
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
          cd ${{ env.PROJECT_DIRECTORY }}
          npm run test:ci
      - name: Check coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: '${{ env.PROJECT_DIRECTORY }}/coverage/lcov.info'
          min_coverage: 75
